/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedDeudasRouteImport } from './routes/_authenticated/deudas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCajaMenorRouteImport } from './routes/_authenticated/caja-menor'
import { Route as AuthenticatedAhorrosRouteImport } from './routes/_authenticated/ahorros'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeudasRoute = AuthenticatedDeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaMenorRoute = AuthenticatedCajaMenorRouteImport.update({
  id: '/caja-menor',
  path: '/caja-menor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAhorrosRoute = AuthenticatedAhorrosRouteImport.update({
  id: '/ahorros',
  path: '/ahorros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ahorros': typeof AuthenticatedAhorrosRoute
  '/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ahorros': typeof AuthenticatedAhorrosRoute
  '/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ahorros': typeof AuthenticatedAhorrosRoute
  '/_authenticated/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/deudas': typeof AuthenticatedDeudasRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ahorros'
    | '/caja-menor'
    | '/calendario'
    | '/deudas'
    | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ahorros'
    | '/caja-menor'
    | '/calendario'
    | '/deudas'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ahorros'
    | '/_authenticated/caja-menor'
    | '/_authenticated/calendario'
    | '/_authenticated/deudas'
    | '/_authenticated/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deudas': {
      id: '/_authenticated/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof AuthenticatedDeudasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja-menor': {
      id: '/_authenticated/caja-menor'
      path: '/caja-menor'
      fullPath: '/caja-menor'
      preLoaderRoute: typeof AuthenticatedCajaMenorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ahorros': {
      id: '/_authenticated/ahorros'
      path: '/ahorros'
      fullPath: '/ahorros'
      preLoaderRoute: typeof AuthenticatedAhorrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAhorrosRoute: typeof AuthenticatedAhorrosRoute
  AuthenticatedCajaMenorRoute: typeof AuthenticatedCajaMenorRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDeudasRoute: typeof AuthenticatedDeudasRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAhorrosRoute: AuthenticatedAhorrosRoute,
  AuthenticatedCajaMenorRoute: AuthenticatedCajaMenorRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDeudasRoute: AuthenticatedDeudasRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
