/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedMiembrosRouteImport } from './routes/_authenticated/miembros'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedDeudasRouteImport } from './routes/_authenticated/deudas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCajaMenorRouteImport } from './routes/_authenticated/caja-menor'
import { Route as AuthenticatedAhorrosRouteImport } from './routes/_authenticated/ahorros'
import { Route as AuthenticatedAbonosRouteImport } from './routes/_authenticated/abonos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiembrosRoute = AuthenticatedMiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeudasRoute = AuthenticatedDeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaMenorRoute = AuthenticatedCajaMenorRouteImport.update({
  id: '/caja-menor',
  path: '/caja-menor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAhorrosRoute = AuthenticatedAhorrosRouteImport.update({
  id: '/ahorros',
  path: '/ahorros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbonosRoute = AuthenticatedAbonosRouteImport.update({
  id: '/abonos',
  path: '/abonos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abonos': typeof AuthenticatedAbonosRoute
  '/ahorros': typeof AuthenticatedAhorrosRoute
  '/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/miembros': typeof AuthenticatedMiembrosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abonos': typeof AuthenticatedAbonosRoute
  '/ahorros': typeof AuthenticatedAhorrosRoute
  '/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/miembros': typeof AuthenticatedMiembrosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/abonos': typeof AuthenticatedAbonosRoute
  '/_authenticated/ahorros': typeof AuthenticatedAhorrosRoute
  '/_authenticated/caja-menor': typeof AuthenticatedCajaMenorRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/deudas': typeof AuthenticatedDeudasRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/miembros': typeof AuthenticatedMiembrosRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/abonos'
    | '/ahorros'
    | '/caja-menor'
    | '/calendario'
    | '/deudas'
    | '/historial'
    | '/miembros'
    | '/panel'
    | '/invitacion/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/abonos'
    | '/ahorros'
    | '/caja-menor'
    | '/calendario'
    | '/deudas'
    | '/historial'
    | '/miembros'
    | '/panel'
    | '/invitacion/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/abonos'
    | '/_authenticated/ahorros'
    | '/_authenticated/caja-menor'
    | '/_authenticated/calendario'
    | '/_authenticated/deudas'
    | '/_authenticated/historial'
    | '/_authenticated/miembros'
    | '/_authenticated/panel'
    | '/invitacion/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/miembros': {
      id: '/_authenticated/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof AuthenticatedMiembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deudas': {
      id: '/_authenticated/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof AuthenticatedDeudasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja-menor': {
      id: '/_authenticated/caja-menor'
      path: '/caja-menor'
      fullPath: '/caja-menor'
      preLoaderRoute: typeof AuthenticatedCajaMenorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ahorros': {
      id: '/_authenticated/ahorros'
      path: '/ahorros'
      fullPath: '/ahorros'
      preLoaderRoute: typeof AuthenticatedAhorrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abonos': {
      id: '/_authenticated/abonos'
      path: '/abonos'
      fullPath: '/abonos'
      preLoaderRoute: typeof AuthenticatedAbonosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonosRoute: typeof AuthenticatedAbonosRoute
  AuthenticatedAhorrosRoute: typeof AuthenticatedAhorrosRoute
  AuthenticatedCajaMenorRoute: typeof AuthenticatedCajaMenorRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDeudasRoute: typeof AuthenticatedDeudasRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedMiembrosRoute: typeof AuthenticatedMiembrosRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonosRoute: AuthenticatedAbonosRoute,
  AuthenticatedAhorrosRoute: AuthenticatedAhorrosRoute,
  AuthenticatedCajaMenorRoute: AuthenticatedCajaMenorRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDeudasRoute: AuthenticatedDeudasRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedMiembrosRoute: AuthenticatedMiembrosRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
